// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU_FDsNCwWG5OUhxRwye3_zY_s9ZkRdoo',
    appId: '1:1073227153390:web:83f6b7265562f88719d8ff',
    messagingSenderId: '1073227153390',
    projectId: 'bi-lang-d5e5e',
    authDomain: 'bi-lang-d5e5e.firebaseapp.com',
    storageBucket: 'bi-lang-d5e5e.firebasestorage.app',
    measurementId: 'G-11XFN6YX82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-JELXC46IEExEeyKdJM7Btm6OcAFo7ME',
    appId: '1:1073227153390:android:0ac6c8c55a0bed5c19d8ff',
    messagingSenderId: '1073227153390',
    projectId: 'bi-lang-d5e5e',
    storageBucket: 'bi-lang-d5e5e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeLP4Nzxj9LmJ9mbFzG7LqomFq2dLzbR0',
    appId: '1:1073227153390:ios:9dc690cfca2bacd119d8ff',
    messagingSenderId: '1073227153390',
    projectId: 'bi-lang-d5e5e',
    storageBucket: 'bi-lang-d5e5e.firebasestorage.app',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAU_FDsNCwWG5OUhxRwye3_zY_s9ZkRdoo',
    appId: '1:1073227153390:web:357892dc96c43c9519d8ff',
    messagingSenderId: '1073227153390',
    projectId: 'bi-lang-d5e5e',
    authDomain: 'bi-lang-d5e5e.firebaseapp.com',
    storageBucket: 'bi-lang-d5e5e.firebasestorage.app',
    measurementId: 'G-GZXD53BWQK',
  );
}
